config/routes.rb
Wouldupay::Application.routes.draw do
  get "pages/home"

  get "pages/help"

  get "pages/about"

  get "pages/contact"

  resources :crowds
  resources :users

  root :to => 'welcome#index'

  match "home" => 'pages#home'
  match "help" => 'pages#help'
  match "about" => 'pages#about'
  match "contact" => 'pages#contact'

end

app/models/crowd.rb
class Crowd < ActiveRecord::Base
  attr_accessible :description, :image, :price, :title, :user_id
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :email, :name
  has_many :crowds
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/crowds_controller.rb
class CrowdsController < ApplicationController
  # GET /crowds
  # GET /crowds.json
  def index
    @crowds = Crowd.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @crowds }
    end
  end

  # GET /crowds/1
  # GET /crowds/1.json
  def show
    @crowd = Crowd.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @crowd }
    end
  end

  # GET /crowds/new
  # GET /crowds/new.json
  def new
    @crowd = Crowd.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @crowd }
    end
  end

  # GET /crowds/1/edit
  def edit
    @crowd = Crowd.find(params[:id])
  end

  # POST /crowds
  # POST /crowds.json
  def create
    @crowd = Crowd.new(params[:crowd])

    respond_to do |format|
      if @crowd.save
        format.html { redirect_to @crowd, notice: 'Crowd was successfully created.' }
        format.json { render json: @crowd, status: :created, location: @crowd }
      else
        format.html { render action: "new" }
        format.json { render json: @crowd.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /crowds/1
  # PUT /crowds/1.json
  def update
    @crowd = Crowd.find(params[:id])

    respond_to do |format|
      if @crowd.update_attributes(params[:crowd])
        format.html { redirect_to @crowd, notice: 'Crowd was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @crowd.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /crowds/1
  # DELETE /crowds/1.json
  def destroy
    @crowd = Crowd.find(params[:id])
    @crowd.destroy

    respond_to do |format|
      format.html { redirect_to crowds_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def help
  end

  def about
  end

  def contact
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /users
  # GET /users.json
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def full_title title
     "WouldUpay"
  end

end

app/helpers/crowds_helper.rb
module CrowdsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/crowds/_form.html.erb
<%= form_for(@crowd) do |f| %>
  <% if @crowd.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@crowd.errors.count, "error") %> prohibited this crowd from being saved:</h2>

      <ul>
      <% @crowd.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :price %><br />
    <%= f.number_field :price %>
  </div>
  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :image %><br />
    <%= f.text_field :image %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.number_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/crowds/edit.html.erb
<h1>Editing crowd</h1>

<%= render 'form' %>

<%= link_to 'Show', @crowd %> |
<%= link_to 'Back', crowds_path %>

app/views/crowds/index.html.erb
<h1>Listing crowds</h1>

<table>
  <tr>
    <th>Price</th>
    <th>Title</th>
    <th>Description</th>
    <th>Image</th>
    <th>User</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @crowds.each do |crowd| %>
  <tr>
    <td><%= crowd.price %></td>
    <td><%= crowd.title %></td>
    <td><%= crowd.description %></td>
    <td><%= crowd.image %></td>
    <td><%= crowd.user_id %></td>
    <td><%= link_to 'Show', crowd %></td>
    <td><%= link_to 'Edit', edit_crowd_path(crowd) %></td>
    <td><%= link_to 'Destroy', crowd, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Crowd', new_crowd_path %>

app/views/crowds/new.html.erb
<h1>New crowd</h1>

<%= render 'form' %>

<%= link_to 'Back', crowds_path %>

app/views/crowds/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Price:</b>
  <%= @crowd.price %>
</p>

<p>
  <b>Title:</b>
  <%= @crowd.title %>
</p>

<p>
  <b>Description:</b>
  <%= @crowd.description %>
</p>

<p>
  <b>Image:</b>
  <%= @crowd.image %>
</p>

<p>
  <b>User:</b>
  <%= @crowd.user_id %>
</p>


<%= link_to 'Edit', edit_crowd_path(@crowd) %> |
<%= link_to 'Back', crowds_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    "application", media: "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <!--[if lt IE 9]>
  <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
  <![endif]-->
</head>
<body>
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "sample app", '#', id: "logo" %>
      <nav>
        <ul class="nav pull-right">
          <li><%= link_to "Home",    '#' %></li>
          <li><%= link_to "Help",    '#' %></li>
          <li><%= link_to "Sign in", '#' %></li>
        </ul>
      </nav>
    </div>
  </div>
</header>
<div class="container">
  <%= yield %>
</div>
</body>
</html>

app/views/pages/about.html.erb
<h1>Pages#about</h1>
<p>Find me in app/views/pages/about.html.erb</p>

app/views/pages/contact.html.erb
<h1>Pages#contact</h1>
<p>Find me in app/views/pages/contact.html.erb</p>

app/views/pages/help.html.erb
<h1>Pages#help</h1>
<p>Find me in app/views/pages/help.html.erb</p>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Email</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.name %></td>
    <td><%= user.email %></td>
    <td><%= link_to 'Show', user %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @user.name %>
</p>

<p>
  <b>Email:</b>
  <%= @user.email %>
</p>


<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>